export const cartEnglish: Record<string, string> = {
  'Sua seleção': 'Your selection',
  'Peças escolhidas por você.': 'Pieces you selected.',
  'Fechar sacola': 'Close bag',
  'Sua seleção está vazia.': 'Your bag is empty.',
  'Explore a coleção e encontre algo para levar ou presentear.': 'Explore the collection and find something to keep or give as a gift.',
  'Continuar comprando': 'Continue shopping',
  'Remover': 'Remove',
  'Para acompanhar': 'To complement your selection',
  'Destaques da coleção que combinam com sua seleção.': 'Collection highlights that pair well with your selection.',
  'Peças para acompanhar sua seleção': 'Pieces to complement your selection',
  'Navegar pelas sugestões': 'Browse suggestions',
  'Ver sugestões anteriores': 'View previous suggestions',
  'Ver próximas sugestões': 'View next suggestions',
  'Sugestões para acompanhar': 'Suggestions to complement your selection',
  'Com esta peça, seu pedido ganha frete grátis.': 'Add this piece and your order qualifies for free shipping.',
  'Você ganhou frete grátis neste pedido.': 'You have free shipping on this order.',
  'Frete fixo PAC R$ 39,90': 'Fixed shipping via PAC R$ 39.90',
  'Grátis a partir de R$ 500 em produtos': 'Free on R$ 500 or more in products',
  'Grátis': 'Free',
  'Finalizar pedido': 'Checkout',
  'Sem criar conta · Pagamento pela InfinitePay': 'No account required · Payment via InfinitePay',
  'Continuar escolhendo': 'Keep browsing',

  'Igreja do Quadrado (P)': 'Church of the Quadrado (Small)',
  'Igreja do Quadrado (M)': 'Church of the Quadrado (Medium)',
  'Igreja do Quadrado (GG) — Luminária': 'Church of the Quadrado (Large) — Luminary',
  'Igrejinha Luminária de Trancoso': 'Trancoso Church Luminary',
  'Casinha Luminária': 'Ceramic House Luminary',
  'Miniatura do Quadrado de Trancoso para Pendurar': 'Hanging Miniature of the Trancoso Quadrado',
  'Cruzeiro do Quadrado': 'Quadrado Cross',
  'Móbile Trancoso em Cerâmica': 'Trancoso Ceramic Mobile',
  'Estatueta Iemanjá em Cerâmica': 'Iemanjá Ceramic Figurine',
  'Nossa Senhora Grande': 'Large Our Lady Figurine',
  'Presépio em Cerâmica': 'Ceramic Nativity Set',
  'Casal de Pretos-Velhos em Cerâmica': 'Pretos-Velhos Couple in Ceramic',
  'Nossa Senhora Aparecida': 'Our Lady of Aparecida',
  'Divino Espírito Santo para Pendurar': 'Hanging Holy Spirit Plaque',
  'Terço em Cerâmica': 'Ceramic Rosary',
  'Rosário Trancoso em Cerâmica': 'Trancoso Ceramic Rosary',
  'Esfera Decorativa': 'Decorative Ceramic Sphere',
  'Colar da Igreja do Quadrado': 'Quadrado Church Necklace',
  'Ímã da Igrejinha de Trancoso': 'Trancoso Church Magnet',

  'Subtotal': 'Subtotal',
  'Total': 'Total',
  'Frete': 'Shipping',
};
