export const catalogEnglish: Record<string, string> = {
  "Encontre uma peça": "Find a piece",
  "Igrejinha, luminária, presente…": "Church, luminary, gift…",
  "Ordenar por": "Sort by",
  "Ordenar peças": "Sort pieces",
  "Filtrar por categoria": "Filter by category",
  "Todas": "All",
  "Faixa de preço": "Price range",
  "Todos os valores": "All prices",
  "Limpar filtros": "Clear filters",
  "Nenhum resultado": "No results",
  "Essa busca não encontrou uma peça.": "No pieces matched your search.",
  "Tente outro nome ou amplie a faixa de preço. Você também pode explorar toda a coleção.": "Try another name or a wider price range. You can also explore the full collection.",
  "Ver toda a coleção": "View the full collection",
  "Destaques": "Featured",
  "Maior preço": "Highest price",
  "Menor preço": "Lowest price",
  "Nome": "Name",
  "Fé e devoção": "Faith & devotion",
  "Trancoso": "Trancoso",
  "Igrejinhas": "Churches",
  "Decoração": "Decor",
  "Presentes": "Gifts",
  "Sugestões de peças": "Piece suggestions",
  "Até R$ 150": "Up to R$ 150",
  "Até R$ 300": "Up to R$ 300",
  "Até R$ 500": "Up to R$ 500",
  "Até R$ 1.000": "Up to R$ 1.000",
  "Até R$ 1.500": "Up to R$ 1.500",
  "Até R$ 3.000": "Up to R$ 3.000",
  "Acima de R$ 3.000": "Over R$ 3.000"
};
