export const internationalEnglish: Record<string, string> = {
  "Escolha suas peças e informe o país de destino. Confirmamos a disponibilidade do serviço, o frete e o prazo antes do pagamento.": "Choose your pieces and tell us the destination country. We confirm shipping availability, cost and delivery estimate before payment.",
  "Clientes com entrega fora do Brasil não precisam informar CPF/CNPJ. Customers receiving orders outside Brazil do not need a Brazilian CPF/CNPJ.": "Customers receiving orders outside Brazil do not need a Brazilian CPF/CNPJ.",
  "Como as peças têm tamanhos diferentes, confirmamos peso, embalagem, serviço disponível, prazo e eventuais restrições do destino antes de cobrar o frete.": "As pieces vary in size, we confirm weight, packaging, available service, delivery time and destination restrictions before quoting shipping.",
  "Você pode informar qualquer país ou território. A disponibilidade do envio é confirmada antes do pagamento.": "You can enter any country or territory. Shipping availability is confirmed before payment.",
  "Impostos, taxas ou exigências da alfândega de destino podem variar conforme o país. Customs duties, taxes or import requirements may vary by destination.": "Customs duties, taxes or import requirements may vary by destination.",
  "O serviço disponível depende do país, do peso, das dimensões, do conteúdo e das regras aduaneiras do destino.": "The available service depends on the country, weight, dimensions, contents and destination customs rules.",
  "Como funciona:": "How it works:",
  " escolha as peças → informe o destino → receba a cotação → confirme o pagamento → enviamos a encomenda.": " choose your pieces → enter the destination → receive the shipping quote → confirm payment → we ship your order.",
  "Do Quadrado para o mundo · From Trancoso to the world": "From Trancoso to the world",
  "Envio internacional · International shipping": "International shipping",
  "Destino · Destination": "Destination",
  "Frete internacional cotado antes do pagamento · International shipping quoted before payment.": "International shipping quoted before payment.",
  "Nome completo · Full name": "Full name",
  "E-mail · Email": "Email",
  "Telefone / WhatsApp · Phone / WhatsApp ": "Phone / WhatsApp ",
  "País ou território · Country or territory": "Country or territory",
  "Cidade · City": "City",
  "Estado / Província / Região · State / Province / Region ": "State / Province / Region ",
  "(se houver / if applicable)": "(if applicable)",
  "Código postal · Postal code ": "Postal code ",
  "Endereço de entrega · Delivery address": "Delivery address",
  "Observações · Notes ": "Notes ",
  "(opcional / optional)": "(optional)",
  "Solicitar cotação · Request shipping quote": "Request shipping quote",
  "Você não paga o frete nesta etapa. Primeiro confirmamos o valor real do envio. · You do not pay shipping at this stage. We confirm the actual shipping cost first.": "You do not pay shipping at this stage. We confirm the actual shipping cost first.",
  "Sua seleção · Your selection": "Your selection",
  "Produtos · Products": "Products",
  "Frete internacional · International shipping": "International shipping",
  "A cotar · To quote": "To quote",
  "Você pode consultar o destino agora ou adicionar suas peças antes. · You can check your destination now or add your pieces first.": "You can check your destination now or add your pieces first.",
  "Explorar coleção · Shop the collection": "Shop the collection",
  "Seu nome / Your name": "Your name",
  "Ex.: Portugal / e.g. United States": "e.g. United States",
  "Cidade / City": "City",
  "Informações importantes para a entrega / Delivery notes": "Delivery notes",
  "Resumo da cotação internacional / International quote summary": "International quote summary",
  "Como funciona o envio internacional / How international shipping works": "How international shipping works",
  "Informe seu nome / Enter your full name.": "Enter your full name.",
  "Informe um e-mail válido / Enter a valid email.": "Enter a valid email.",
  "Informe seu telefone ou WhatsApp com código do país / Enter your phone or WhatsApp with country code.": "Enter your phone or WhatsApp with country code.",
  "Informe o país ou território de destino / Enter the destination country or territory.": "Enter the destination country or territory.",
  "Informe a cidade de destino / Enter the destination city.": "Enter the destination city.",
  "Informe o endereço de entrega / Enter the delivery address.": "Enter the delivery address.",
  "(com código do país / with country code)": "(with country code)",
  "Peças na sacola · Pieces in your bag": "Pieces in your bag",
  "Escolha suas peças · Choose your pieces": "Choose your pieces"
};
